# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-15 02:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='County',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Fish',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Lake',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('altitude', models.FloatField(blank=True, null=True)),
                ('size', models.FloatField(blank=True, null=True)),
                ('rank', models.FloatField(default=0.0)),
            ],
        ),
        migrations.CreateModel(
            name='StockingData',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField(blank=True, null=True)),
                ('amount', models.IntegerField(blank=True, null=True)),
                ('lake', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Lake')),
            ],
        ),
        migrations.AddField(
            model_name='fish',
            name='stocking_data',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.StockingData'),
        ),
        migrations.AddField(
            model_name='county',
            name='lake',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Lake'),
        ),
    ]
