# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-15 03:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='county',
            name='lake',
        ),
        migrations.RemoveField(
            model_name='fish',
            name='stocking_data',
        ),
        migrations.AddField(
            model_name='lake',
            name='county',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='app.County'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='stockingdata',
            name='fish',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='app.Fish'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='county',
            name='name',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
    ]
