# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-16 00:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_lake_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockingdata',
            name='url',
            field=models.CharField(default='', max_length=1000),
            preserve_default=False,
        ),
    ]
