# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-18 04:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_stockingdata_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='LakeStats',
            fields=[
                ('lake', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='app.Lake')),
                ('min_size', models.FloatField(blank=True, null=True)),
                ('max_size', models.FloatField(blank=True, null=True)),
                ('min_alt', models.FloatField(blank=True, null=True)),
                ('max_alt', models.FloatField(blank=True, null=True)),
            ],
        ),
    ]
