# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-18 18:31
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_lakestats'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lakestats',
            name='lake',
        ),
        migrations.AddField(
            model_name='lakestats',
            name='avg_alt',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lakestats',
            name='avg_size',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lakestats',
            name='id',
            field=models.AutoField(default='', primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='lakestats',
            name='last_updated',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
