# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-18 18:33
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20161118_1033'),
    ]

    operations = [
        migrations.AddField(
            model_name='lakestats',
            name='last_updated',
            field=models.DateField(blank=True, default=datetime.date.today, null=True),
        ),
    ]
