# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-18 18:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20161118_1031'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lakestats',
            name='last_updated',
        ),
    ]
