# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-18 19:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_lakestats_last_updated'),
    ]

    operations = [
        migrations.AddField(
            model_name='lakestats',
            name='total',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
